blog/admin/views.py
from flask import Blueprint, render_template, redirect, request, url_for
from flask import session, abort, jsonify
from ..db import db, Users, Passages, Tags, Details, Friends, Comments
from ..db import Talks, Reports
from ..db.pagination import Pagination
from ..weibo import get_client
import functools
import time

admin_module = Blueprint('admin_module', __name__,
        template_folder='templates', static_folder='static')


def admin_session(func):
    @functools.wraps(func)
    def wrapper(*args, **kw):
        if 'root' not in session:
            return redirect(url_for('index_module.index'))
        return func(*args, **kw)
    return wrapper


@admin_module.route('/index/', defaults={'page':1})
@admin_module.route('/index/<int:page>')
@admin_session
def index(page):
    limit = 10
    site = {'index': 'active'}
    site['home'] = 'class=active'
    if 'tag' not in request.args:
        passages = Passages.get_all_passages_exc_deleted(limit=limit,
                                                         offset=(page-1)*limit)
        count = Passages.count_admin()
        pagination = Pagination(page, limit, count)
        return render_template('admin/index.html', site=site, passage_list=passages, pagination=pagination)
    elif Tags.is_avaliable(request.args.get('tag')):
        passages = Tags.get_passages_for_list(request.args.get('tag'), False) 
        return render_template('admin/index.html', site=site, passage_list=passages)
    else:
        abort(404)


@admin_module.route('/display_passage', methods=['POST'])
@admin_session
def display_passage():
    if 'pid' not in request.form or not request.form['pid']:
        abort(400)
    status = True if Passages.display(request.form['pid']) else False
    db.session.commit()
    return jsonify(status=status)


@admin_module.route('/rollback_passage', methods=['POST'])
@admin_session
def rollback_passage():
    if 'pid' not in request.form or not request.form['pid']:
        abort(400)
    status = True if Passages.rollback(request.form['pid']) else False
    db.session.commit()
    return jsonify(status=status)


@admin_module.route('/dust')
@admin_session
def index_dust():
    site = {'index': 'active'}
    site['dust'] = 'class=active'
    passages = Passages.get_all_passages_deleted()
    passages.reverse()
    return render_template('admin/dust_passage.html', site=site,
                           dust_passages=passages)
   

@admin_module.route('/tags')
@admin_session
def index_tags():
    site = {'index': 'active'}
    site['tags'] = 'class=active'
    tag_list = Tags.get_all_tags()
    return render_template('admin/tag_list.html', site=site, tags = tag_list)


@admin_module.route('/reports')
@admin_session
def reports():
    site = {'index': 'active'}
    site['reports'] = 'class=active'
    reports = {}
    reports['comments'] = Comments.get_reports()
    reports['talks'] = Talks.get_reports()
    reports['sum'] = len(reports['comments']) + len(reports['talks'])
    return render_template('admin/reports.html', site=site, reports=reports)


@admin_module.route('/edit')
@admin_session
def edit():
    site = {'edit': 'active'}
    tagList = Tags.get_all_tags()
    if 'pid' not in request.args:
        return render_template('admin/edit.html', site=site, tags=tagList)
    passage = Passages.get_passage_by_id(request.args.get('pid'))
    if not passage:
        abort(404)
    passage.is_draft = True
    for t in tagList:
        if t['tag'] in [x.tag for x in passage.tags]:
            t['checked'] = True
        else:
            t['checked'] = False
    db.session.commit()
    return render_template('admin/edit.html',
                           site=site,
                           tags=tagList,
                           passage=passage)


@admin_module.route('/config/')
@admin_session
def config():
    site = {'config': 'active'}
    config = Details.get_info()
    return render_template('admin/config.html', site=site, info=config)


@admin_module.route('/friend/')
@admin_session
def friend():
    site = {'friend': 'active'}
    friends = Friends.get_all_friends_exc_deleted()
    return render_template('admin/friend.html', site=site, friends=friends)


@admin_module.route('/upload_passage', methods=['POST'])
@admin_session
def upload_passage():
    # print request.form
    # print type(request.form.getlist('tags[]'))
    # print request.form.getlist('tags[]')
    _infoForPassage = ['title', 'content', 'description']
    assert request.method == 'POST'
    assert request.path == '/admin/upload_passage'
    for need in _infoForPassage:
        if need not in request.form or not request.form[need]:
            abort(400)
    p = Passages(
            title=request.form['title'],
            content=request.form['content'],
            description=request.form['description'],
            )
    p.set_tags(request.form.getlist('tags'))
    db.session.add(p)
    db.session.commit()
    return redirect(url_for('.index'))


@admin_module.route('/update_passage', methods=['POST'])
@admin_session
def update_passage():
    p = Passages.get_passage_by_id(request.form['pid'])
    p.update_tags(request.form.getlist('tags'))
    p.update_passage(
            title=request.form['title'],
            content=request.form['content'],
            description=request.form['description']
            )
    db.session.commit()
    return redirect(url_for('.index'))


@admin_module.route('/add_tag', methods=['POST'])
@admin_session
def add_tag():
    if not 'tagList' in request.json or not request.json['tagList']:
        abort(400)
    t_list = []
    for item in request.json['tagList']:
        if Tags.is_avaliable(item):
            pass
        else:
            t = Tags(tag=item)
            db.session.add(t)
            t_list.append(t)
    db.session.commit()
    result = [{'tid': x.id, 'tag': x.tag} for x in t_list]
    if t_list:
        return jsonify(status=True, result=result)
    else:
        return jsonify(status=False)


@admin_module.route('/del_passage', methods=['POST'])
@admin_session
def del_passage():
    if 'pid' not in request.form or\
            not Passages.get_passage_by_id(request.form['pid']):
        abort(400)
    p = Passages.get_passage_by_id(request.form['pid'])
    p.del_passage()
    db.session.commit()
    return jsonify(status=True)


@admin_module.route('/recycle_passage', methods=['POST'])
@admin_session
def recycle_passage():
    if 'pid' not in request.form or\
            not Passages.get_passage_by_id(request.form['pid']):
        abort(400)
    p = Passages.get_passage_by_id(request.form['pid'])
    p.recycle_passage()
    db.session.commit()
    return jsonify(status=True)


@admin_module.route('/del_tag', methods=['POST'])
@admin_session
def del_tag():
    assert request.form['tag']
    Tags.del_tag(request.form['tag'])
    db.session.commit()
    return jsonify(status=True)

@admin_module.route('/update_tag', methods=['POST'])
@admin_session
def update_tag():
    assert request.form['origin']
    if Tags.update_tag(request.form['origin'], request.form['newTag']):
        db.session.commit()
        return jsonify(status=True)
    else:
        return jsonify(status=False)


@admin_module.route('/update_config', methods=['POST'])
@admin_session
def update_config():
    _info = ['description']
    for x in _info:
        if x not in request.form or not request.form[x]:
            abort(400)
    if Details.is_default():
        d = Details(description=request.form['description'])
        db.session.add(d)
    else:
        Details.update_info(description=request.form['description'])
    db.session.commit()
    return redirect(url_for('.config'))


@admin_module.route('/add_friend', methods=['POST'])
@admin_session
def add_friend():
    _info = ['friend', 'link']
    for x in _info:
        if x not in request.form or not request.form[x]:
            abort(400)
    if Friends.is_registered_by_name(request.form['friend']):
        return jsonify(status=False)
    f = Friends(link=request.form['link'],
                description=request.form['friend'])
    db.session.add(f)
    db.session.commit()
    return jsonify(status=True)


@admin_module.route('/update_friend', methods=['POST'])
@admin_session
def update_friend():
    _info = ['friend', 'link', 'fid']
    for x in _info:
        if x not in request.form or not request.form[x]:
            abort(400)
    if not Friends.is_registered_by_id(request.form['fid']):
        return jsonify(status=False)
    Friends.update_friend(fid=request.form['fid'], 
                          friend=request.form['friend'],
                          link=request.form['link'])
    db.session.commit()
    return jsonify(status=True)


@admin_module.route('/del_friend', methods=['POST'])
@admin_session
def del_friend():
    if 'fid' not in request.form or not request.form['fid'] \
            or not Friends.is_registered_by_id(request.form['fid']):
        abort(400)
    Friends.del_friend(request.form['fid'])
    db.session.commit()
    return jsonify(status=True)


@admin_module.route('/del_comment', methods=['POST'])
@admin_session
def del_comment():
    if 'mode' not in request.form:
        abort(404)
    if request.form['mode'] == 'reply':
        if 'cid' not in request.form:
            abort(400)
        c = Comments.get_comment_by_id(request.form['cid'])
        if not c or c.is_delete:
            return jsonify(status=False)
        c.is_delete = True
        db.session.commit()
        return jsonify(status=True)
    elif request.form['mode'] == 'talk':
        if 'tid' not in request.form:
            abort(400)
        t = Talks.get_talk_by_id(request.form['tid'])
        if not t or t.is_delete:
            return jsonify(status=False)
        t.is_delete = True
        db.session.commit()
        return jsonify(status=True)
    else:
        abort(400)

@admin_module.route('/ignore_report', methods=['POST'])
@admin_session
def ignore_report():

blog/templates/layout/base.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{%if my_site_config%}
	<meta name="description" content="{{my_site_config['info']['summary'] | d('我手记我心, Zhangyu Chen的个人博客')}}">
	<meta name="keywords" content="{{my_site_config['info']['keyword'] | d('web backend')}}">
	<title>{{my_site_config['info']['title'] | d('Zhangyu Chen的个人博客')}}</title>
	{%else%}
	<meta name="description" content="我手记我心, Zhangyu Chen的个人博客">
	<meta name="keywords" content="web backend">
	<title>Zhangyu Chen的个人博客</title>
	{%endif%}
	<!-- <link rel="stylesheet" href="/static/lib/dist/css/bootstrap.min.css"> -->
	<link href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" href="/static/css/base.css">

	<!-- <script src="http://tjs.sjs.sinajs.cn/open/api/js/wb.js?appkey=2858452607&debug=true" type="text/javascript" charset="utf-8"></script> -->
{%block headScript%}{%endblock headScript%}

</head>
<body>
<div id="body-container">		
{%block body%}
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <div id="flash-container">
    {% for category, message in messages %}
      <p class="flash-msg text-center {{ category }}">{{ message }}</p>
    {% endfor %}
    </div>
  {% endif %}
{% endwith %}
	<nav class="navbar navbar-default" role="navigation">
	  <div class="container-fluid top-nav">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="{{url_for('index_module.index')}}">首页</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	      	{%if 'root' in session%}
	      	<li><a href="{{url_for('admin_module.index')}}">控制台</a></li>
	      	{%endif%}
	        <li><a href="{{url_for('index_module.archive')}}">归档</a></li>
	        <li><a href="{{url_for('index_module.about')}}">关于</a></li>
	      </ul>
	      <ul class="nav navbar-nav navbar-right">
			 <li>
			{%if session['username'] and session['profile_url']%}
			<a id='user-login' href="http://weibo.com/{{session['profile_url']}}">{{session['username']}}</a>
			<a id="logout" href="{{url_for('index_module.logout')}}">logout</a>
			{%else%}
			<a href="{{url_for('index_module.login')}}">微博登陆</a>
			{%endif%}
			 </li>
	        <!-- <li><a href="#"></a></li> -->
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>


{%block container%}{%endblock%}

{%endblock%}
</div>
</body>
<script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>
<script src="http://cdn.bootcss.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<!-- <script src="/static/lib/dist/js/jquery-1.11.0.min.js"></script>
<script src="/static/lib/dist/js/bootstrap.min.js"></script> -->
<script>
$(document).ready(function(){
	$('.flash-msg').each(function(){
		$(this).fadeOut(1800);
	})
});
</script>

<!-- cdn -->

{%block footScript%}{%endblock%}
</html>