blog/index/views.py
# -*-coding:utf-8-*-

from flask import Blueprint, render_template, redirect, request, url_for
from flask import session, abort, jsonify, flash
from itsdangerous import URLSafeSerializer, BadSignature
from datetime import timedelta
from ..db import db, Users, Details, Passages, Comments, Friends
from ..db import Tags, Talks, Votes, Reports
from ..db.pagination import Pagination
from ..weibo import get_client
from ..config import info as site_info
from ..mail import send_mail
import functools
import math
import time
import functools

def _get_referer():
    return session['Referer'] if 'Referer' in session else url_for('.index')

def _get_config():
    temp = {'title': site_info['site']['name'],
            'summary': site_info['site']['summary'],
            'kwywords': site_info['site']['keywords']}
    config_in_db = Details.get_info()
    for key in config_in_db:
        temp[key] = config_in_db[key]
    return {'info': temp,
            'friends':Friends.get_all_friends_exc_deleted()}

def _test_for_int(value):
    try:
        result = int(value)
        return False if result < 0 else True
    except ValueError:
        return False

def _config_for_reply():
    """
    check the post data about comment info
    return True if reliable
    """
    if 'cid' not in request.form or \
            not _test_for_int(request.form['cid']):
        return False
    return True

def _config_for_talk():
    """
    check the post data about talk info
    return True if reliable
    """
    if 'tid' not in request.form or \
            not _test_for_int(request.form['tid']):
        return False
    return True

def online_session(func):
    @functools.wraps(func)
    def wrapper(*args, **kw):
        if 'id' not in session:
            return jsonify(status=False)
        return func(*args, **kw)
    return wrapper

def get_serializer():
    return URLSafeSerializer(site_info['site']['serializer'])

def get_activation_link(user):
    s = get_serializer()
    payload = s.dumps(user.id)
    return url_for('.activate', payload=payload, _external=True)

def send_reply_mail(user, url):
    assert user.is_activated
    sitename = site_info['site']['name']
    content = ('You have new messages in ' + sitename + ' \n'
               'For more details, click the following link\n\n' + url)
    send_mail(user.email, 'new messages in ' + sitename, content)
    return


index_module = Blueprint('index_module', __name__,
        template_folder='templates', static_folder='static')


@index_module.route('/')
@index_module.route('/index')
def index():
    if 'page' not in request.args or \
            not _test_for_int(request.args.get('page')):
        page = 0
    else:
        page = int(request.args.get('page'))
    ps = Passages.get_all_passages_for_index(offset=page*5)
    # when page not found
    if len(ps) == 0 and page != 0:
        abort(404)
    else:
        has_next = False if not page and not len(ps) or \
            Passages.is_end(ps[len(ps)-1].id) else True
        has_previous = True if page else False
    page_info = {'page': page,
                 'has_previous': has_previous, 
                 'has_next': has_next}
    return render_template('index/index.html', 
                           my_site_config=_get_config(), 
                           passages=ps,
                           page=page_info)


@index_module.route('/archive/', defaults={'page':1})
@index_module.route('/archive/<int:page>')
def archive(page):
    limit = 10
    ps = Passages.get_all_passages_for_list(limit=limit,
                                            offset=(page-1)*limit,
                                            kind='all')
    count = Passages.count_display()
    if not ps and page != 1:
        abort(404)
    pagination = Pagination(page, limit, count)
    return render_template('index/categories.html', 
                           my_site_config=_get_config(),
                           passages=ps,
                           pagination=pagination)


@index_module.route('/categories/<kind>/')
def categories(kind):
    if not Tags.is_avaliable(kind):
        abort(404)
    ps = Passages.get_all_passages_for_list(kind=kind)
    return render_template('index/categories.html', 
                           my_site_config=_get_config(),
                           passages=ps,
                           kind=kind)


@index_module.route('/passage')
def passage():
    if 'pid' not in request.args or \
            not _test_for_int(request.args.get('pid')):
        abort(404)

    p = Passages.get_passage_by_id(request.args.get('pid'))
    if not p or p.is_draft == True:
        abort(404)
    nav = {'prev': p.prev_item, 'next': p.next_item}
    return render_template('index/passage.html', 
                           my_site_config=_get_config(),
                           passage=p,
                           nav=nav)

@index_module.route('/about')
def about():
    return render_template('index/about.html',
                           my_site_config=_get_config())

@index_module.route('/comment', methods=['POST'])
@online_session
def comment():
    if 'pid' not in request.form or \
            'comment' not in request.form or \
            not request.form['comment'] or \
            not Passages.is_shown(request.form['pid']):
        abort(404)
    c = Comments(content=request.form['comment'],
                 pid=request.form['pid'],
                 uid=session['id'])
    db.session.add(c)
    db.session.commit()
    root = Users.query.get(1)
    if site_info['email']['engine'] == 'on' and root.is_activated:
        url = 'http://' + site_info['site']['url'] + url_for('.passage') + \
            '?pid=' + str(request.form['pid'])
        send_reply_mail(root, url)
    return jsonify(status=True)


@index_module.route('/reply', methods=['POST'])
@online_session
def reply():
    if 'content' not in request.form or \
            not request.form['content'] or \
            not _config_for_reply():
        return jsonify(status=False)
    c = Comments.get_comment_by_id(request.form['cid'])
    if not c:
        return jsonify(status=False)
    db.session.add(Talks(request.form['content'],
                         c.pid,
                         request.form['cid'],
                         session['id'],
                         c.uid))
    db.session.commit()
    if site_info['email']['engine'] == 'on' and c.user.is_activated:
        url = 'http://' + site_info['site']['url'] + url_for('.passage') + \
            '?pid=' + str(c.pid)
        send_reply_mail(c.user, url)
    return jsonify(status=True, refresh=True)


@index_module.route('/talk', methods=['POST'])
@online_session
def talk():
    if 'content' not in request.form or \
            not request.form['content'] or \
            not _config_for_talk():
        return jsonify(status=False)
    t = Talks.get_talk_by_id(request.form['tid'])
    if not t:
        return jsonify(status=False)
    db.session.add(Talks(request.form['content'],
                         t.pid,
                         t.cid,
                         session['id'],
                         t.f_uid))
    db.session.commit()
    if site_info['email']['engine'] == 'on' and t.f_user.is_activated:
        url = 'http://' + site_info['site']['url'] + url_for('.passage') + \
            '?pid=' + str(t.pid)
        send_reply_mail(t.f_user, url)
    return jsonify(status=True, refresh=True)


@index_module.route('/vote', methods=['POST'])
@online_session
def vote():
    if 'mode' not in request.form:
        abort(404)
    if request.form['mode'] == 'reply':
        if not _config_for_reply():
            return jsonify(status=False)
        c = Comments.get_comment_by_id(request.form['cid'])
        if not c or c.is_delete:
            return jsonify(status=False)
        v = Votes.get_vote(c.id, session['id'], False)
        if v is not None:
            db.session.delete(v)
            c.vote_ups -= 1
            result = False
        else:
            db.session.add(Votes(c.id, session['id'], False))
            c.vote_ups += 1
            result = True
        db.session.commit()
        return jsonify(status=True, result=result)
    elif request.form['mode'] == 'talk':
        if not _config_for_talk():
            return jsonify(status=False)
        t = Talks.get_talk_by_id(request.form['tid'])
        if not t or t.is_delete:
            return jsonify(status=False)
        v = Votes.get_vote(t.id, session['id'], True)
        if v is not None:
            db.session.delete(v)
            t.vote_ups -= 1
            result = False
        else:
            db.session.add(Votes(t.id, session['id'], True))
            t.vote_ups += 1
            result = True
        db.session.commit()
        return jsonify(status=True, result=result)
    else:
        return jsonify(status=False)


@index_module.route('/report_reply', methods=['POST'])
@index_module.route('/report_talk', methods=['POST'])
@online_session
def report():
    if 'mode' not in request.form or \
            'content' not in request.form or \
            not request.form['content']:
        abort(404)
    if request.form['mode'] == 'report_reply':
        if not _config_for_reply():
            return jsonify(status=False)
        c = Comments.get_comment_by_id(request.form['cid'])
        if not c or c.is_delete:
            return jsonify(status=False)
        db.session.add(Reports(c.id, 
                               session['id'],
                               request.form['content'],
                               False))
        db.session.commit()
    elif request.form['mode'] == 'report_talk':
        if not _config_for_talk():
            return jsonify(status=False)
        t = Talks.get_talk_by_id(request.form['tid'])
        if not t or t.is_delete:
            return jsonify(status=False)
        db.session.add(Reports(t.id,
                               session['id'],

blog/index/templates/index/about.html
{% import "module.html" as module %}
{%extends "index/layout/index.html"%}
{%block indexHeadScript%}

{%endblock indexHeadScript%}
{%block rightPart%}

<p class="pre-wrap">{{my_site_config['info']['description']}}</p>
<p>最后更新: {{module.render_time(my_site_config['info']['pubdate'])}}</p>

{%endblock rightPart%}

blog/index/templates/index/categories.html
{%import "module.html" as module%}
{%extends "index/layout/index.html"%}
{%block indexHeadScript%}
<link rel="stylesheet" href="{{url_for('.static', filename='css/categories.css')}}">
{%endblock indexHeadScript%}
{%block rightPart%}
<div class="passage-list">
	{%for passage in passages%}
	<div class="passage">
		<a target="blank" href="{{url_for('.passage')}}?pid={{passage.id}}" class="passage-link">{{passage.title}}</a>
		<span class="detail text-right">
			<div>
				<i class="fa fa-calendar"></i>{{module.render_time(passage.pubdate)}}
			</div>
			<div>
				<i class="fa fa-tags"></i>
				{%for tag in passage.tags%}
				<a href="{{url_for('.categories', kind=tag.tag)}}" class="tag-item">{{tag.tag}}</a>
				{%endfor%}
			</div>
		</span>
	</div>	
	{%endfor%}

</div>

{%if pagination%}
	{{module.render_pagination(pagination, '.archive')}}
{%endif%}
{%endblock rightPart%}

blog/index/templates/index/email.html
{%extends "layout/base.html"%}
{%block headScript%}
{{super()}}
	<link rel="stylesheet" href="{{url_for('.static', filename='css/email.css')}}">
{%endblock headScript%}
{%block body%}
<div class="jumbotron">
	<div class="wrapper">
		<h2>在这里你可以填写你常用的邮箱,以便及时收到回复</h2>
	  	<h4>你也可以选择留空</h4>
	  	<div id="form">
	  		<form action="{{url_for('index_module.add_email')}}" method="post" role="form">
	  			<div class="form-group">
	  				<input type="email" id="address" name="address" placeholder="常用邮箱" class="form-control">
	  			</div>
	  			<button type="submit" class="btn btn-success">Submit</button>
	  		</form>
	  	</div>
	</div>
</div>
{%endblock body%}

blog/index/templates/index/index.html
{%import "module.html" as module%}
{%extends "index/layout/index.html"%}
{%block indexHeadScript%}
	<link rel="stylesheet" href="{{url_for('.static', filename='css/index.css')}}">
{%endblock indexHeadScript%}
{%block rightPart%}
{%for passage in passages%}
<div class="article">
	<p class="article-item pubdate">
		<i class="fa fa-calendar fa-2x"></i>
 			{{module.render_time(passage.pubdate)}}
	 		<span class="tag-list text-right">
			<i class="fa fa-tags"></i>
			{%for tag in passage.tags%}
			<span class="tag"><a href="{{url_for('.categories', kind=tag.tag)}}" class="text-link">{{tag.tag}}</a></span>
			{%endfor%}
		</span>
	</p>
	<a target="blank" href="{{url_for('.passage')}}?pid={{passage.id}}" class="article-item title">{{passage.title}}</a>
	<p class="article-item description">
		{{passage.description}}<a target="blank" href="{{url_for('.passage')}}?pid={{passage.id}}" title="more" class="more"><i class="fa fa-chevron-circle-right"></i></a>
	</p>
</div>
{%endfor%}

<div class="bottom-nav text-center">
	
	<nav>
	  <ul class="pager">
	    {%if page['has_previous']%}
	    <li><a id="previous" href="{{url_for('.index')+'?page='}}{{page['page']-1}}">Previous</a></li>
	    {%else%}
	    <li class="disabled"><a href="#" id="previous">Previous</a></li>
	    {%endif%}
	    {%if page['has_next']%}
	    <li><a id="next" href="{{url_for('.index')+'?page='}}{{page['page']+1}}">Next</a></li>
	    {%else%}
	    <li class="disabled"><a href="#" id="next">Next</a></li>
	    {%endif%}
	  </ul>
	</nav>

</div>

{%endblock rightPart%}

blog/index/templates/index/passage.html
{%import "module.html" as module%}
{%extends "index/layout/index.html"%}
{%block indexHeadScript%}
<link rel="stylesheet" href="{{url_for('.static', filename='css/passage.css')}}">
<link rel="stylesheet" href="/static/lib/highlight/styles/monokai_sublime.css">
{%endblock indexHeadScript%}
{%block rightPart%}

{%macro render_username(user)%}
{%if user.is_root%}
<a href="{{url_for('index_module.about')}}" class="text-link">{{user.username}}</a>&nbsp;<span class="text-danger">(作者)</span>
{%else%}
<a href="{{user.profile_url}}" class="text-link">{{user.username}}</a>
{%endif%}
{%endmacro%}

{%macro render_votes(votes)%}
	{%if votes%}<span class="votes">({{votes}})</span>{%endif%}
{%endmacro%}

{%macro admin_view(item)%}
	<span class="action reply"><i class="fa fa-reply"></i>&nbsp;回复</span>
	<span class="action vote-up"><i class="fa fa-thumbs-o-up"></i>&nbsp;点赞{{render_votes(item.vote_ups)}}</span>
	{%if 'root' in session and session['root']%}
		{%if item.is_warning %}
			<span class="text-danger">举报次数({{item.is_warning}})</span>&nbsp;
		{%endif%}
		<span class="action delete"><i class="fa fa-trash-o"></i>&nbsp;删除</span>	
	{%else%}
		<span class="action report"><i class="fa fa-flag"></i>&nbsp;举报</span>
	{%endif%}
{%endmacro%}



<div id="passage">
	{%if passage%}
		<div id="passage-item">
			<h1>{{passage.title}}</h1>
			<div class="tag-list">
				<i class="fa fa-tags"></i>
					{%for t in passage.tags%}
						<a href="{{url_for('.categories', kind=t.tag)}}" class="tag">{{t.tag}}</a>
					{%endfor%}
			</div>
			<div id="passage-content">
				<div id="waitting"><i class="fa fa-spinner fa-spin fa-3x"></i></div>
			</div>

			<div>Zhangyu Chen@{{module.render_time(passage.pubdate)}}</div>

			<div class="passage-link">
				
					<span id="previous">
						{%if nav['prev']%}
							上一篇&nbsp;<a href="{{url_for('.passage')}}?pid={{nav['prev'].id}}" class="noul">{{nav['prev'].title}}</a>
						{%endif%}
					</span>
				
					<span id="next">
						{%if nav['next']%}
							下一篇&nbsp;<a href="{{url_for('.passage')}}?pid={{nav['next'].id}}" class="noul">{{nav['next'].title}}</a>
						{%endif%}
					</span>
			</div>

		</div>
	{%endif%}
	<hr>
	
	<div class="comment-list">
		{%for comment in passage.comments%}
			{%if not comment.is_delete%}
				<div class="comment-item">
					<div class="profile-image">
						<img src="{{comment.user.profile_img}}">	
					</div>
					<div class="comment-session" cid="{{comment.id}}">
						{{render_username(comment.user)}}
						<div class="comment-content">{{comment.content}}</div>
						<span class="comment-time">{{module.render_time(comment.pubdate)}}</span>
						{{admin_view(comment)}}
					</div>
				</div>
				<hr>
				{%for talk in comment.talks%}
					{%if not talk.is_delete%}
						<div class="comment-item comment-item-reply">
							<div class="profile-image">
								<img src="{{talk.f_user.profile_img}}">	
							</div>
							<div class="comment-session" mode="talk" cid="{{talk.cid}}" tid="{{talk.id}}">
								{{render_username(talk.f_user)}}&nbsp;回复&nbsp;{{render_username(talk.t_user)}}
								<div class="comment-content">{{talk.content}}</div>
								<span class="comment-time">{{module.render_time(talk.pubdate)}}</span>
								{{admin_view(talk)}}
							</div>
						</div>	
						<hr>
					{%endif%}
				{%endfor%}
			{%endif%}
		{%endfor%}
		
	</div>

	<div class="comment-box">
		<div id="emoji">
			<div id="emoji-list">
				<span>[]~(￣▽￣)~*</span>
				<span>(￣ˇ￣)</span>
				<span>(￣﹏￣)</span>
				<span>(￣ε(#￣)</span>
				<span>(￣.￣)</span>
				<span>╮(￣▽￣)╭</span>
				<span>(￣▽￣)~*</span>
				<span>(⊙ˍ⊙)</span>
				<span>∑( ° △ °|||)︴</span>
				<span>(=￣ω￣=)</span>
				<span>(＞﹏＜)</span>
				<span>m( _　_ )m</span>
				<span>(oﾟωﾟo)</span>
				<span>(σ‘・д･)σ</span>
				<span>(。・ˍ・。)</span>
				<span>(Θ３Θ)</span>
				<span>╰（￣▽￣）╭</span>
				<span>→_→</span>
				<span>←_←</span>
			</div>
			<div class="arrow-down"></div>
		</div>
		<div class="box-head"><i class="fa fa-smile-o emoji-toggle"></i></div>
		<div class="box-body">
			<textarea id="comment-input" rows="6"></textarea>
		</div>
		<div class="text-right">
			<button class="btn btn-success" id="comment">发布评论</button>	
		</div>
	</div>


</div>

<div class="modal fade" id="reply-dialog" tabindex="-1" role="dialog" aria-labelledby="reply-box" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="reply-box"></h4>
      </div>
      <div class="modal-body">
      	  <textarea id="reply-input" rows="10" class="form-control"></textarea>
          <p class="text-danger" id="msg"></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
        <button type="button" class="btn btn-primary" id="submit-btn">提交</button>
      </div>
    </div>
  </div>
</div>

{%endblock rightPart%}
{%block footScript%}
{{super()}}
	<script src="/static/lib/marked.min.js"></script>
	<script src="/static/lib/highlight/highlight.pack.js"></script>
	<script src="{{url_for('.static', filename='js/passage.js')}}"></script>
	{%if 'root' in session and session['root']%}
	<script src="{{url_for('.static', filename='js/admin.js')}}"></script>
	{%endif%}
{%endblock%}